- id: '1645971282848'
  alias: Movimento detectado
  description: Envia notificação para os residentes quando for detectado movimento
  trigger:
  - platform: state
    entity_id: binary_sensor.sensor_movimento_entrada
    from: 'on'
  condition: []
  action:
  - service: script.notificacao_movimento
    data: {}
  mode: single
- id: '1650133608109'
  alias: Movimento detectado pela câmera -  Início
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-camera1-started
  condition: []
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.camera1_motion_detected
  - service: script.notificacao_movimento_pela_camera
    data: {}
  mode: single
- id: '1650133636349'
  alias: Movimento detectado pela câmera - Fim
  description: ''
  trigger:
  - platform: webhook
    webhook_id: motioneye-camera1-ended
  condition: []
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.camera1_motion_detected
  mode: single
- id: '1652721686782'
  alias: Notificação fuga de gás ou fumaça
  description: ''
  trigger:
  - platform: mqtt
    topic: cozinha/gas_fumaca
  condition:
  - condition: numeric_state
    entity_id: sensor.sensor_cozinha_gasfumaca
    above: '1500'
  action:
  - service: script.notificacao_fuga_de_gas_ou_fumaca
    data: {}
  mode: single
- id: '1653309744634'
  alias: Firebase - Envia os dados dos sensores para o Firebase
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: ha2firebase.sendcollecteddata
    data: {}
  mode: restart
- id: '1653309953708'
  alias: Firebase - Envia as imagens das detecções de movimento para o Firebase
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: ha2firebase.senddetectionimages
    data: {}
  mode: restart
