# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template: !include template.yaml

# Custom

homeassistant:
  media_dirs:
    media: /media
    # recording: /mnt/recordings

# Camera
camera:
  - name: Camera entrada - Streaming
    platform: mjpeg
    mjpeg_url: http://10.0.0.111/

input_boolean:
  camera1_motion_detected:
    name: Camera1 - Motion detected
    icon: mdi:eye

# Sensores
sensor:
  - name: sensor_cozinha_temperature
    platform: mqtt
    state_topic: "cozinha/temperatura"
    qos: 1

  - name: sensor_cozinha_umidade
    platform: mqtt
    state_topic: "cozinha/umidade"
    qos: 1

  - name: sensor_cozinha_gasfumaca
    platform: mqtt
    state_topic: "cozinha/gas_fumaca"
    qos: 1

  - name: sensor_entrada_movimento
    platform: mqtt
    state_topic: "entrada/movimento"
    qos: 1

binary_sensor:
  - platform: mqtt
    name: Sensor movimento entrada
    state_topic: "entrada/movimento"
    payload_on: "on"
    payload_off: "off"
    device_class: motion
    
  - platform: template
    sensors:
      camera1_motion:
        friendly_name: Camera motion
        value_template: "{{ is_state('input_boolean.camera1_motion_detected', 'on') }}"
        device_class: motion

